import os
import time
import pyfiglet
os.system('clear')
print("Code By SantriXploiter")
time.sleep(1)
os.system('clear')
os.system('xdg-open https://www.youtube.com/channel/UCG8EAqQdcDzphpluzrJWt3Q')
print("\33[36;1m")
head = pyfiglet.figlet_format("Hack Planet")
print (head)
a = ("bulan")
b = ("mars")
c = ("Venus")
d = ("Saturnus")
print("[-----------------------]")
print("[1] Geser", a)
print("[2] Geser", b)
print("[3] Geser", c)
print("[4] Geser", d)
print("[------------------------]")
print
pilih = int(input("pilih : "))
if pilih == 1:
	print("\33[37;1m")
	time.sleep(1)
	derajat = int(input("geser brp derajat : "))
	time.sleep(1)
	print("Sedang menggeser", a ,"dengan", derajat ,"derajat")
	time.sleep(3)
	print("\33[36;1m")
	print(a, "Telah di Geser Sebanyak", derajat ,"derajat")
elif pilih == 2:
	print("\33[37;1m")
	time.sleep(1)
	derajat = int(input("geser brp derajat : "))
	time.sleep(1)
	print("Sedang menggeser", b ,"dengan", derajat ,"derajat")
	time.sleep(3)
	print("\33[36;1m")
	print(b, "Telah di Geser Sebanyak", derajat ,"derajat")
elif pilih == 3:
	print("\33[37;1m")
	time.sleep(1)
	derajat = int(input("geser brp derajat : "))
	time.sleep(1)
	print("Sedang menggeser", c ,"dengan", derajat ,"derajat")
	time.sleep(3)
	print("\33[36;1m")
	print(c, "Telah di Geser Sebanyak", derajat ,"derajat")
elif pilih == 4:
	print("\33[37;1m")
	time.sleep(1)
	derajat = int(input("geser brp derajat : "))
	time.sleep(1)
	print("Sedang menggeser", d ,"dengan", derajat ,"derajat")
	time.sleep(3)
	print("\33[36;1m")
	print(d, "Telah di Geser Sebanyak", derajat ,"derajat")
else:
	print("\33[37;1m")
	print("Berantem Bos? baca Pilihanya apa aja")
